modLoader="javafml"
loaderVersion="[41,)"
license="MIT License"
issueTrackerURL = "https://t.me/jarmenya52"
logoFile="Oblozkha.png"

[[mods]]
modId="manastaffs"
version="1.19"
displayName="ManaStaffs"
credits="Thanks for this manastaffs Mod goes to Java" #optional
authors="Oppakolba"
description='''
Hi this is my first mod "manastaffs" good games and learn lorem ipsum'''

[[mixins]]
config="mixins.manastaffs.json"

[[dependencies.manastaffs]]
    modId="forge"
    mandatory=true
    versionRange="[41,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.manastaffs]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19,1.20)"
    ordering="NONE"
    side="BOTH"
