modLoader="javafml"
loaderVersion="[41,)"
license="MIT License"
issueTrackerURL = "https://t.me/jarmenya52"
logoFile="Oblozkha.png"

[[mods]]
modId="canes"
version="1.19"
displayName="Canes"
credits="Thanks for this Canes Mod goes to Java" #optional
authors="Oppakolba"
description='''
Hi this is my first mod "Canes" good games and learn lorem ipsum'''


[[dependencies.canes]]
    modId="forge"
    mandatory=true
    versionRange="[41,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.canes]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19,1.20)"
    ordering="NONE"
    side="BOTH"
